#spring:
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:prod;Mode=Oracle
#    #    url: jdbc:h2:file:~/Workspace/H2/routing;Mode=Oracle
#    username: sa
#    password:
#    initialization-mode: always
#  jpa:
#    open-in-view: false
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: false
#    hibernate:
#      ddl-auto: none
#    #      naming:
#    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate.jdbc.time_zone: UTC
#
#
##logging:
##  level.org.springframework.jdbc: debug
#
#integration:
#  sftp:
#    charset: Cp852
#    temp-dir: /Users/nzcs/uploads/sftp/temp/
#    source:
#      host: 192.168.0.59
#      port: 22
#      user: nzcs
#      password: 5101
#      input-dir: uploads/sftp/source/
#      success-output-dir: uploads/sftp/success_output/
#      faulty-output-dir: uploads/sftp/faulty_output/
